<?php
declare(strict_types=1);

// Keep this JSON endpoint isolated from accidental output generated by
// included helpers/libraries. json_response() clears this buffer before
// sending the final response.
ob_start();

require_once __DIR__ . '/helpers.php';
require_once __DIR__ . '/mail/email-helper.php';
require_once __DIR__ . '/bookings/booking-expiry-helper.php';
require_once __DIR__ . '/bookings/booking-audit-helper.php';
require_once __DIR__ . '/calendar/ics-helper.php';
require_once __DIR__ . '/security/public-token-helper.php';
require_once __DIR__ . '/offers/offer-pricing-helper.php';

apply_cors_headers();

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    json_response(false, 'Only POST requests are allowed.', 405);
}

rate_limit_or_fail('submit_booking', 6, 15);

$data = read_request_data();
$fullName = clean_string($data['full_name'] ?? '', 150);
$email = strtolower(clean_string($data['email'] ?? '', 190));
$phone = clean_string($data['phone'] ?? '', 50);
$isBookingForOther = !empty($data['is_booking_for_other']) && filter_var($data['is_booking_for_other'], FILTER_VALIDATE_BOOLEAN);
$stayingGuestName = clean_string($data['staying_guest_name'] ?? '', 150);
$stayingGuestEmail = strtolower(clean_string($data['staying_guest_email'] ?? '', 190));
$stayingGuestPhone = clean_string($data['staying_guest_phone'] ?? '', 50);
$stayingGuestNote = clean_string($data['staying_guest_note'] ?? '', 3000);
$roomName = clean_string($data['room_name'] ?? '', 150);
$checkInDate = clean_string($data['check_in_date'] ?? '', 20);
$checkOutDate = clean_string($data['check_out_date'] ?? '', 20);
$guests = (int) ($data['guests'] ?? 0);
$message = clean_string($data['message'] ?? '', 3000);
$paymentMethod = strtolower(clean_string($data['payment_method'] ?? 'Cash', 30));
$isOnlinePayment = in_array($paymentMethod, ['payhere', 'online', 'pay online'], true);
$isCashPayment = in_array($paymentMethod, ['cash', 'pay on arrival'], true);

if (!$isCashPayment && !$isOnlinePayment) {
    json_response(false, 'Please select a valid payment method.', 422, ['error_code' => 'INVALID_PAYMENT_METHOD']);
}

// Keep the PayHere flow intact for future use, but do not create a booking when
// online payment is intentionally disabled in the environment.
if ($isOnlinePayment && !ONLINE_PAYMENT_ENABLED) {
    json_response(false, 'Online payment is not available at the moment. Please use Pay on Arrival.', 200, [
        'severity' => 'warning',
        'error_code' => 'ONLINE_PAYMENT_DISABLED',
        'fallback_payment_method' => 'Cash',
    ]);
}

if ($fullName === '' || $email === '' || $phone === '' || $roomName === '' || $checkInDate === '' || $checkOutDate === '' || $guests < 1) {
    json_response(false, 'Please complete all required booking details.', 422, ['error_code' => 'MISSING_REQUIRED_FIELDS']);
}

if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
    json_response(false, 'Please enter a valid email address, for example name@example.com.', 422, ['error_code' => 'INVALID_EMAIL']);
}

if ($stayingGuestEmail !== '' && !filter_var($stayingGuestEmail, FILTER_VALIDATE_EMAIL)) {
    json_response(false, 'Please enter a valid staying guest email address.', 422);
}

if (!$isBookingForOther) {
    $stayingGuestName = '';
    $stayingGuestEmail = '';
    $stayingGuestPhone = '';
    $stayingGuestNote = '';
}

if (!is_valid_date($checkInDate) || !is_valid_date($checkOutDate)) {
    json_response(false, 'Please select valid check-in and check-out dates.', 422, ['error_code' => 'INVALID_DATES']);
}

$today = new DateTimeImmutable('today');
$checkIn = DateTimeImmutable::createFromFormat('Y-m-d', $checkInDate);
$checkOut = DateTimeImmutable::createFromFormat('Y-m-d', $checkOutDate);

if (!$checkIn || !$checkOut) {
    json_response(false, 'Please enter valid check-in and check-out dates.', 422);
}

if ($checkIn < $today) {
    json_response(false, 'Check-in cannot be earlier than today.', 422, ['error_code' => 'INVALID_DATES']);
}

if ($checkOut < $checkIn) {
    json_response(false, 'Check-out must be after check-in.', 422, ['error_code' => 'INVALID_DATES']);
}

if ($checkOutDate === $checkInDate) {
    $checkOutDate = $checkIn->modify('+1 day')->format('Y-m-d');
    $checkOut = DateTimeImmutable::createFromFormat('Y-m-d', $checkOutDate);
}

if ($guests > 20) {
    json_response(false, 'Please enter a valid number of guests.', 422);
}

$subtotalAmount = calculate_booking_amount($roomName, $checkInDate, $checkOutDate);
$amount = $subtotalAmount;

if ($amount <= 0) {
    json_response(false, 'Unable to calculate booking amount for the selected room.', 422);
}

$bookingId = 0;
$bookingCommitted = false;

try {
    $pdo = get_db_connection();
    offer_ensure_booking_snapshot_schema($pdo);
    $nights = max(1, (int) $checkIn->diff($checkOut)->days);
    $offerPrice = offer_best_price($pdo, $subtotalAmount, $checkInDate, $nights, 1, $guests);
    $amount = $offerPrice['total'];
    expire_pending_bookings($pdo, null, true);

    // Initialize the ICS tables before starting the booking transaction.
    // Running CREATE TABLE IF NOT EXISTS inside a MySQL transaction causes an
    // implicit commit and later produces "There is no active transaction".
    if (ics_enabled()) {
        ensure_ics_schema($pdo);
    }

    $pdo->beginTransaction();

    $roomStmt = $pdo->prepare("SELECT id, max_guests, status FROM rooms WHERE room_name = :room_name LIMIT 1");
    $roomStmt->execute([':room_name' => $roomName]);
    $room = $roomStmt->fetch();

    if (!$room || ($room['status'] ?? '') !== 'Available') {
        $pdo->rollBack();
        json_response(false, 'Please select a valid available room.', 422);
    }

    if ($guests > (int) ($room['max_guests'] ?? 0)) {
        $pdo->rollBack();
        json_response(false, 'This room cannot accommodate the selected number of guests. Please reduce the guest count or choose multiple rooms.', 422, ['error_code' => 'ROOM_CAPACITY_EXCEEDED']);
    }

    $conflict = $pdo->prepare(
        "SELECT id, check_in_date, check_out_date
         FROM bookings
         WHERE room_name = :room_name
           " . active_booking_conflict_sql() . "
           AND :requested_check_in < check_out_date
           AND :requested_check_out > check_in_date
         LIMIT 1"
    );
    $conflict->execute([
        ':room_name' => $roomName,
        ':hold_cutoff' => booking_hold_cutoff_datetime(),
        ':requested_check_in' => $checkInDate,
        ':requested_check_out' => $checkOutDate,
    ]);

    if ($conflict->fetch() || ics_room_conflict($pdo, (int) $room['id'], $checkInDate, $checkOutDate)) {
        $pdo->rollBack();
        json_response(false, 'This room was just booked for the selected dates. Please choose another room or change your dates.', 409, ['available' => false, 'error_code' => 'ROOM_UNAVAILABLE']);
    }

    $columnStmt = $pdo->query('SHOW COLUMNS FROM bookings');
    $bookingColumns = array_flip(array_column($columnStmt->fetchAll(), 'Field'));

    $bookingValues = [
        'full_name' => $fullName,
        'email' => $email,
        'phone' => $phone,
        'is_booking_for_other' => $isBookingForOther ? 1 : 0,
        'staying_guest_name' => $stayingGuestName !== '' ? $stayingGuestName : null,
        'staying_guest_email' => $stayingGuestEmail !== '' ? $stayingGuestEmail : null,
        'staying_guest_phone' => $stayingGuestPhone !== '' ? $stayingGuestPhone : null,
        'staying_guest_note' => $stayingGuestNote !== '' ? $stayingGuestNote : null,
        'room_name' => $roomName,
        'check_in_date' => $checkInDate,
        'check_out_date' => $checkOutDate,
        'guests' => $guests,
        'message' => $message,
        'status' => 'Pending',
        'payment_status' => 'Payment Pending',
        'amount' => $amount,
        'subtotal_amount' => $offerPrice['subtotal'],
        'discount_amount' => $offerPrice['discount'],
        'applied_offer_id' => $offerPrice['offer_id'],
        'applied_offer_title' => $offerPrice['offer_title'],
        'offer_snapshot_json' => $offerPrice['snapshot'],
        'currency' => PAYMENT_CURRENCY,
        'ip_address' => get_client_ip(),
        'user_agent' => mb_substr($_SERVER['HTTP_USER_AGENT'] ?? '', 0, 255),
    ];

    $insertColumns = [];
    $insertPlaceholders = [];
    $insertParams = [];

    foreach ($bookingValues as $column => $value) {
        if (isset($bookingColumns[$column])) {
            $insertColumns[] = $column;
            $insertPlaceholders[] = ':' . $column;
            $insertParams[':' . $column] = $value;
        }
    }

    $insertColumns[] = 'created_at';
    $insertPlaceholders[] = 'NOW()';
    $insertColumns[] = 'updated_at';
    $insertPlaceholders[] = 'NOW()';

    $stmt = $pdo->prepare(
        'INSERT INTO bookings (' . implode(', ', $insertColumns) . ') VALUES (' . implode(', ', $insertPlaceholders) . ')'
    );
    $stmt->execute($insertParams);

    $bookingId = (int) $pdo->lastInsertId();

    $bookingNumber = 'BK-' . str_pad((string) $bookingId, 5, '0', STR_PAD_LEFT);
    $cashOrderId = '';
    $cashBillUrl = '';

    // Pay on Arrival gets its payment row immediately so the bill page can show
    // the complete booking/payment details. PayHere creates its payment row only
    // when create-checkout-session.php starts the gateway checkout.
    if ($isCashPayment) {
        $cashOrderId = 'CASH-' . str_pad((string) $bookingId, 5, '0', STR_PAD_LEFT);

        $paymentStmt = $pdo->prepare(
            "INSERT INTO payments
                (booking_id, order_id, amount, currency, status, method, gateway_response, created_at, updated_at)
             VALUES
                (:booking_id, :order_id, :amount, :currency, 'Payment Pending', 'Cash', NULL, NOW(), NOW())"
        );
        $paymentStmt->execute([
            ':booking_id' => $bookingId,
            ':order_id' => $cashOrderId,
            ':amount' => $amount,
            ':currency' => PAYMENT_CURRENCY,
        ]);

        $amountForToken = number_format($amount, 2, '.', '');
        $cashBillToken = create_public_token('payment-status', [
            'order_id' => $cashOrderId,
            'booking_id' => $bookingId,
            'amount' => $amountForToken,
        ], PUBLIC_LINK_TTL_SECONDS);

        $publicBaseUrl = defined('FRONTEND_URL') && FRONTEND_URL !== ''
            ? FRONTEND_URL
            : (defined('PUBLIC_APP_URL') && PUBLIC_APP_URL !== '' ? PUBLIC_APP_URL : APP_BASE_URL);
        $cashBillUrl = rtrim((string) $publicBaseUrl, '/') . '/booking-bill?' . http_build_query([
            'booking_id' => $bookingId,
            'order_id' => $cashOrderId,
            'token' => $cashBillToken,
        ]);
    }

    $pdo->commit();
    $bookingCommitted = true;

    // Audit/email helpers may create or upgrade their own tables. Run them only
    // after the booking and Cash payment are committed so optional side effects
    // can never roll back or implicitly commit the core booking transaction.
    booking_audit_log($pdo, $bookingId, 'booking_created', 'Booking Created', 'Customer submitted booking details and a pending booking was created.', [
        'room_name' => $roomName,
        'amount' => $amount,
        'currency' => PAYMENT_CURRENCY,
        'payment_method' => $isOnlinePayment ? 'PayHere' : 'Cash',
    ]);

    if ($isCashPayment) {
        $emailBooking = $bookingValues;
        $emailBooking['id'] = $bookingId;
        $emailBooking['booking_no'] = $bookingNumber;
        $emailBooking['payment_method'] = 'Cash';
        try {
            send_booking_received_emails($pdo, $emailBooking);
        } catch (Throwable $emailError) {
            error_log('Public Cash booking email error: ' . $emailError->getMessage());
        }
    }

    json_response(true, 'Booking inquiry submitted successfully.', 201, [
        'inquiry_id' => $bookingId,
        'booking_id' => $bookingId,
        'booking_no' => $bookingNumber,
        'amount' => $amount,
        'currency' => PAYMENT_CURRENCY,
        'payment_method' => $isOnlinePayment ? 'PayHere' : 'Cash',
        'order_id' => $cashOrderId !== '' ? $cashOrderId : null,
        'bill_url' => $cashBillUrl !== '' ? $cashBillUrl : null,
        'requires_online_checkout' => $isOnlinePayment,
        'data' => [
            'booking_id' => $bookingId,
            'booking_no' => $bookingNumber,
            'amount' => $amount,
            'currency' => PAYMENT_CURRENCY,
            'payment_method' => $isOnlinePayment ? 'PayHere' : 'Cash',
            'order_id' => $cashOrderId !== '' ? $cashOrderId : null,
            'bill_url' => $cashBillUrl !== '' ? $cashBillUrl : null,
        ],
    ]);
} catch (Throwable $e) {
    if (isset($pdo) && $pdo instanceof PDO && $pdo->inTransaction()) {
        $pdo->rollBack();
    }
    $supportReference = strtoupper(substr(hash('sha256', uniqid('booking-', true)), 0, 8));
    error_log('Booking submit error [' . $supportReference . ']: ' . $e->getMessage());

    // Never tell the customer that booking failed when the complete booking
    // and Cash payment records already exist. This also covers a database
    // driver reporting an error after persistence has actually completed.
    $persistedBookingExists = $bookingCommitted;
    $persistenceVerificationFailed = false;
    if (!$persistedBookingExists && $bookingId > 0) {
        try {
            $verifyPdo = get_db_connection();
            $verifyStmt = $verifyPdo->prepare(
                "SELECT b.id
                 FROM bookings b
                 WHERE b.id = :booking_id
                 LIMIT 1"
            );
            $verifyStmt->execute([':booking_id' => $bookingId]);
            $persistedBookingExists = (bool) $verifyStmt->fetchColumn();
        } catch (Throwable $verificationError) {
            $persistenceVerificationFailed = true;
            error_log('Booking persistence verification failed: ' . $verificationError->getMessage());
        }
    }

    if ($persistedBookingExists && $bookingId > 0) {
        // A database driver can occasionally report an error after MySQL has
        // already persisted the booking. Rebuild the Cash bill link from the
        // stored payment row so a successful booking never loses its redirect.
        $recoveredOrderId = '';
        $recoveredBillUrl = '';

        if ($isCashPayment) {
            try {
                $recoveryPdo = isset($verifyPdo) && $verifyPdo instanceof PDO
                    ? $verifyPdo
                    : get_db_connection();
                $paymentRecoveryStmt = $recoveryPdo->prepare(
                    "SELECT order_id, amount
                     FROM payments
                     WHERE booking_id = :booking_id
                       AND method = 'Cash'
                     ORDER BY id DESC
                     LIMIT 1"
                );
                $paymentRecoveryStmt->execute([':booking_id' => $bookingId]);
                $recoveredPayment = $paymentRecoveryStmt->fetch();

                if ($recoveredPayment) {
                    $recoveredOrderId = (string) ($recoveredPayment['order_id'] ?? '');
                    $recoveredAmount = number_format((float) ($recoveredPayment['amount'] ?? $amount), 2, '.', '');

                    if ($recoveredOrderId !== '') {
                        $recoveredToken = create_public_token('payment-status', [
                            'order_id' => $recoveredOrderId,
                            'booking_id' => $bookingId,
                            'amount' => $recoveredAmount,
                        ], PUBLIC_LINK_TTL_SECONDS);
                        $recoveredPublicBaseUrl = defined('FRONTEND_URL') && FRONTEND_URL !== ''
                            ? FRONTEND_URL
                            : (defined('PUBLIC_APP_URL') && PUBLIC_APP_URL !== '' ? PUBLIC_APP_URL : APP_BASE_URL);
                        $recoveredBillUrl = rtrim((string) $recoveredPublicBaseUrl, '/') . '/booking-bill?' . http_build_query([
                            'booking_id' => $bookingId,
                            'order_id' => $recoveredOrderId,
                            'token' => $recoveredToken,
                        ]);
                    }
                }
            } catch (Throwable $billRecoveryError) {
                error_log('Cash booking bill-link recovery failed: ' . $billRecoveryError->getMessage());
            }
        }

        json_response(true, 'Booking request received successfully. Email delivery may be delayed.', 201, [
            'inquiry_id' => $bookingId,
            'booking_id' => $bookingId,
            'booking_no' => 'BK-' . str_pad((string) $bookingId, 5, '0', STR_PAD_LEFT),
            'amount' => $amount,
            'currency' => PAYMENT_CURRENCY,
            'payment_method' => $isOnlinePayment ? 'PayHere' : 'Cash',
            'order_id' => $recoveredOrderId !== '' ? $recoveredOrderId : null,
            'bill_url' => $recoveredBillUrl !== '' ? $recoveredBillUrl : null,
            'email_delayed' => true,
            'data' => [
                'booking_id' => $bookingId,
                'booking_no' => 'BK-' . str_pad((string) $bookingId, 5, '0', STR_PAD_LEFT),
                'amount' => $amount,
                'currency' => PAYMENT_CURRENCY,
                'payment_method' => $isOnlinePayment ? 'PayHere' : 'Cash',
                'order_id' => $recoveredOrderId !== '' ? $recoveredOrderId : null,
                'bill_url' => $recoveredBillUrl !== '' ? $recoveredBillUrl : null,
            ],
        ]);
    }

    if ($bookingId > 0 && $persistenceVerificationFailed) {
        json_response(false, 'We could not confirm the final booking result. Your booking may already be saved. Please do not submit again. Contact the property with your name and booking dates.', 503, [
            'error_code' => 'BOOKING_OUTCOME_UNKNOWN',
        ]);
    }

    json_response(false, 'The server could not save your booking. Please try once more or contact reception and mention reference ' . $supportReference . '.', 500, [
        'error_code' => 'BOOKING_NOT_SAVED',
        'support_reference' => $supportReference,
    ]);
}
